### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by katiequin335** [wurde/first-steps#17]
When I click "Sign in with github", I get a blank page with this in the url bar.

>http://localhost:3000/auth/github/callback?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdeveloper.github.com%2Fv3%2Foauth%2F%23redirect-uri-mismatch&state=45a073ccf650928a83588406a3d88f51d50524e7e474fcca

**Comment by wurde** [comment]
I came across that also in development. It's a URL mismatch error because the GitHub app I created needs callback URL to match. So I can have it pointing to either the rails rumble URL or to localhost:3000.

**Comment by wurde** [comment]
I'm going to continue to work on this app beyond the competition, so thank you for filing this issue.

**Comment by katiequin335** [comment]
You're welcome! It's a neat concept

**Comment by wurde** [comment]
I've set http://localhost:3000 as the target. I'll switch to the rails rumble URL once all issues are cleared.
