### ISSUE TITLE
As a open source developer I need to sync my GitHub account, so I can see all my public repositories.

### ISSUE THREAD

**Issue by wurde** [wurde/first-steps#2]

**Comment by katiequin335** [comment]
Saw some of your issues on the global issues list, what kind of app is this? Are you using the Github Api?

**Comment by wurde** [comment]
This is my #railsrumble 2015 application. The premise is it'll automate First Steps of an open source project on GitHub.

**Comment by katiequin335** [comment]
Great idea! How many hours in are you?

**Comment by wurde** [comment]
Thank you. I have less than 12 hours to get design into production ;)

**Comment by katiequin335** [comment]
Good luck! I'll check back to see the finished app

**Comment by wurde** [comment]
Glad to know I have the public waffle io board community keeping me honest. I have my fingers crossed and fresh pot of coffee, so that I can stay focused.
